import Image from 'next/image'
import { Navbar } from './components/Navbar'
import './globals.css'
import { Inter } from 'next/font/google'
import Link from 'next/link'

const inter = Inter({ subsets: ['latin'] })

export const metadata = {
  title: 'The posts',
  description: 'Generated by create next app',
}

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <Link href='/'>
          <Image 
            src={'/new-post-sticker-for-social-media-content-vector-23241892.jpg'} 
            alt="NewPost"
            width={80}
            height={80}
          />
        </Link>
        <Navbar/>
        {children}
        </body>
    </html>
  )
}
